# Generated by Django 5.2.8 on 2025-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('softskill', 'Soft Skill')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('host_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True)),
                ('skills', models.ManyToManyField(related_name='projects', to='recursos.skill')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
