# Generated by Django 5.2.8 on 2025-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_project_order_alter_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-published_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='host_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del proyecto', null=True, upload_to='projects/'),
        ),
    ]
